### ISSUE TITLE
Example lists

### ISSUE THREAD

**Issue by arlin** [phylotastic/general-web-ui#2]
Construct a set of at least 20 example lists of species. This can include anything, really.  Some specific lists that would be good to have: 
* a list that is complete for a taxon (e.g., all felidae species) - use to test coverage
* a short list and a long list 
* a list that includes some spelling errors 
* a list that is biologically interesting
* a list that includes common names

Be sure to maintain metadata on each list including display name, source, and explanation.  Eventually these lists will be used in testing, and they will be delivered by a service.

**Comment by hdliv** [comment]
different size lists where some include 'problems', such as small spelling mistakes, synonymy, and extinct taxa were added under the examples folder
